### ISSUE TITLE
is there a tool or library that can be used on android?

### ISSUE THREAD

**Issue by FlamingJay** [currentslab/awesome-vector-search#8]

**Comment by theblackcat102** [comment]
Not that I know of. This does seems to be a very niche but potential market though.

**Comment by wayblink** [comment]
For curiosity, what scenario needs vector search on android?  Considering vector search is very memory consuming.

**Comment by theblackcat102** [comment]
@wayblink I think one common use case would be clustering photo with the same person ( something iOS and android has been supporting for quite a while ). Android phones with RAM > 4G is now common, I think it might be possible to have a cut down int8 version?
